### ISSUE TITLE
MIDITrackView formula

### ISSUE THREAD

**Issue by PhysVasya** [AudioKit/.github#2]
### Description

Hey there! First of all wanna say huge thanks for the framework, was a pleasure to switch from native audio engine, not without some struggling, but still, for purposes of midi playback, thats what i needed.

ive got a question though, tried to search in the repo issues and even watched some of coding in youtube, but couldn’t found any explanation. 
![IMG_0859](https://github.com/AudioKit/.github/assets/84687599/1df8f46e-05d5-44c0-b58e-e062a69fb40d)

### Proposed Solution

Can you please provide some info on MIDITrackView formula used while calculating speed over time timer scrolling? 

### Describe Alternatives You've Considered

—

**Comment by emurray2** [comment]
Hi, thanks for your question! I'm the person responsible for writing this code 3 years ago, and I remember calculating this formula was difficult. The base and inverse are based on the properties of the view, such as length, MIDI ticks, and the note zoom (how zoomed in the user is to the track). What it's trying to do is convert MIDI ticks into pixel values and bpm into a pixel value. You can get the ticks per quarter for a MIDI note (or beat) which gets you the ticks per minute if it's in 4/4. However, this isn't great as MIDI files could have different ticks per quarter or different time signatures.

I wasn't proud of this and made an improved MIDITrackView for the last 2 years. I'm currently waiting on a code review for it before it gets released and will keep you posted.

For now, I would say it's easier to have a timer update at its own view and check the current position of the midi sequencer. You can say something like: sequencer.getCurrentPosition. The new MIDITrackView does this and I hope to release it soon.

**Comment by PhysVasya** [comment]
Thanks for your reply! Well, it makes sense..
Looking forward to seeing the new MIDITrackView implementation. 

I will try the solution of yours, hope the get current position implementation won’t affect performance too much; as our app is hugely loaded during midi playback😅
